// Data parser from the site.
// Paste it in console and you will json object
// const res = [];
// for (const list of arr) {
//   const anchor = list.querySelector("a");
//   const link = anchor.href;
//   const id = anchor.href.split("/task/")[1];
//   const name = anchor.innerText;
//   const [acceptedCount, submissionCount] = list
//     .querySelector("span.detail")
//     .innerText.split(" / ");
//   res.push({
//     id,
//     name,
//     link,
//     acceptedCount: Number(acceptedCount),
//     submissionCount: Number(submissionCount),
//   });
// }

export const questionData = [
  {
    id: "1728",
    name: "Inversion Probability",
    link: "https://cses.fi/problemset/task/1728",
    acceptedCount: 250,
    submissionCount: 1907,
    difficulty: 3,
  },
  {
    id: "2418",
    name: "Grid Path Construction",
    link: "https://cses.fi/problemset/task/2418",
    acceptedCount: 94,
    submissionCount: 378,
    difficulty: 3,
  },
  {
    id: "2402",
    name: "Two Stacks Sorting",
    link: "https://cses.fi/problemset/task/2402",
    acceptedCount: 134,
    submissionCount: 418,
    difficulty: 3,
  },
  {
    id: "1685",
    name: "New Flight Routes",
    link: "https://cses.fi/problemset/task/1685",
    acceptedCount: 267,
    submissionCount: 664,
    difficulty: 3,
  },
  {
    id: "2174",
    name: "Removing Digits II",
    link: "https://cses.fi/problemset/task/2174",
    acceptedCount: 173,
    submissionCount: 387,
    difficulty: 3,
  },
  {
    id: "1727",
    name: "Candy Lottery",
    link: "https://cses.fi/problemset/task/1727",
    acceptedCount: 1160,
    submissionCount: 2415,
    difficulty: 3,
  },
  {
    id: "2081",
    name: "Fixed-Length Paths II",
    link: "https://cses.fi/problemset/task/2081",
    acceptedCount: 1145,
    submissionCount: 2280,
    difficulty: 3,
  },
  {
    id: "1742",
    name: "Robot Path",
    link: "https://cses.fi/problemset/task/1742",
    acceptedCount: 242,
    submissionCount: 433,
    difficulty: 3,
  },
  {
    id: "2423",
    name: "Filling Trominos",
    link: "https://cses.fi/problemset/task/2423",
    acceptedCount: 189,
    submissionCount: 308,
    difficulty: 3,
  },
  {
    id: "1112",
    name: "Required Substring",
    link: "https://cses.fi/problemset/task/1112",
    acceptedCount: 1323,
    submissionCount: 2107,
    difficulty: 3,
  },
  {
    id: "1110",
    name: "Minimal Rotation",
    link: "https://cses.fi/problemset/task/1110",
    acceptedCount: 2304,
    submissionCount: 3653,
    difficulty: 3,
  },
  {
    id: "2134",
    name: "Path Queries II",
    link: "https://cses.fi/problemset/task/2134",
    acceptedCount: 2750,
    submissionCount: 4287,
    difficulty: 3,
  },
  {
    id: "1703",
    name: "Critical Cities",
    link: "https://cses.fi/problemset/task/1703",
    acceptedCount: 334,
    submissionCount: 514,
    difficulty: 3,
  },
  {
    id: "2421",
    name: "Counting Reorders",
    link: "https://cses.fi/problemset/task/2421",
    acceptedCount: 167,
    submissionCount: 255,
    difficulty: 3,
  },
  {
    id: "1673",
    name: "High Score",
    link: "https://cses.fi/problemset/task/1673",
    acceptedCount: 11971,
    submissionCount: 18122,
    difficulty: 3,
  },
  {
    id: "1082",
    name: "Sum of Divisors",
    link: "https://cses.fi/problemset/task/1082",
    acceptedCount: 6754,
    submissionCount: 10206,
    difficulty: 3,
  },
  {
    id: "2430",
    name: "Binary Subsequences",
    link: "https://cses.fi/problemset/task/2430",
    acceptedCount: 236,
    submissionCount: 356,
    difficulty: 3,
  },
  {
    id: "1731",
    name: "Word Combinations",
    link: "https://cses.fi/problemset/task/1731",
    acceptedCount: 4686,
    submissionCount: 6974,
    difficulty: 3,
  },
  {
    id: "2427",
    name: "Letter Pair Move Game",
    link: "https://cses.fi/problemset/task/2427",
    acceptedCount: 160,
    submissionCount: 234,
    difficulty: 3,
  },
  {
    id: "2102",
    name: "Finding Patterns",
    link: "https://cses.fi/problemset/task/2102",
    acceptedCount: 1513,
    submissionCount: 2199,
    difficulty: 3,
  },
  {
    id: "1628",
    name: "Meet in the Middle",
    link: "https://cses.fi/problemset/task/1628",
    acceptedCount: 5446,
    submissionCount: 7872,
    difficulty: 3,
  },
  {
    id: "2194",
    name: "Minimum Euclidean Distance",
    link: "https://cses.fi/problemset/task/2194",
    acceptedCount: 1684,
    submissionCount: 2406,
    difficulty: 3,
  },
  {
    id: "1757",
    name: "Course Schedule II",
    link: "https://cses.fi/problemset/task/1757",
    acceptedCount: 1380,
    submissionCount: 1959,
    difficulty: 3,
  },
  {
    id: "2184",
    name: "Missing Coin Sum Queries",
    link: "https://cses.fi/problemset/task/2184",
    acceptedCount: 318,
    submissionCount: 446,
    difficulty: 3,
  },
  {
    id: "1753",
    name: "String Matching",
    link: "https://cses.fi/problemset/task/1753",
    acceptedCount: 9344,
    submissionCount: 12817,
    difficulty: 3,
  },
  {
    id: "2163",
    name: "Josephus Problem II",
    link: "https://cses.fi/problemset/task/2163",
    acceptedCount: 8569,
    submissionCount: 11738,
    difficulty: 3,
  },
  {
    id: "1111",
    name: "Longest Palindrome",
    link: "https://cses.fi/problemset/task/1111",
    acceptedCount: 3556,
    submissionCount: 4789,
    difficulty: 3,
  },
  {
    id: "2182",
    name: "Divisor Analysis",
    link: "https://cses.fi/problemset/task/2182",
    acceptedCount: 4496,
    submissionCount: 6045,
    difficulty: 3,
  },
  {
    id: "1711",
    name: "Distinct Routes",
    link: "https://cses.fi/problemset/task/1711",
    acceptedCount: 2257,
    submissionCount: 3034,
    difficulty: 3,
  },
  {
    id: "1087",
    name: "Shortest Subsequence",
    link: "https://cses.fi/problemset/task/1087",
    acceptedCount: 2542,
    submissionCount: 3394,
    difficulty: 3,
  },
  {
    id: "2080",
    name: "Fixed-Length Paths I",
    link: "https://cses.fi/problemset/task/2080",
    acceptedCount: 2563,
    submissionCount: 3422,
    difficulty: 2,
  },
  {
    id: "2414",
    name: "List of Sums",
    link: "https://cses.fi/problemset/task/2414",
    acceptedCount: 385,
    submissionCount: 514,
    difficulty: 2,
  },
  {
    id: "1694",
    name: "Download Speed",
    link: "https://cses.fi/problemset/task/1694",
    acceptedCount: 4016,
    submissionCount: 5341,
    difficulty: 2,
  },
  {
    id: "1705",
    name: "Forbidden Cities",
    link: "https://cses.fi/problemset/task/1705",
    acceptedCount: 640,
    submissionCount: 851,
    difficulty: 2,
  },
  {
    id: "1665",
    name: "Coding Company",
    link: "https://cses.fi/problemset/task/1665",
    acceptedCount: 1196,
    submissionCount: 1588,
    difficulty: 2,
  },
  {
    id: "1704",
    name: "Network Renovation",
    link: "https://cses.fi/problemset/task/1704",
    acceptedCount: 801,
    submissionCount: 1063,
    difficulty: 2,
  },
  {
    id: "2180",
    name: "Coin Arrangement",
    link: "https://cses.fi/problemset/task/2180",
    acceptedCount: 273,
    submissionCount: 362,
    difficulty: 2,
  },
  {
    id: "1203",
    name: "Visiting Cities",
    link: "https://cses.fi/problemset/task/1203",
    acceptedCount: 562,
    submissionCount: 744,
    difficulty: 2,
  },
  {
    id: "2429",
    name: "Grid Completion",
    link: "https://cses.fi/problemset/task/2429",
    acceptedCount: 165,
    submissionCount: 218,
    difficulty: 2,
  },
  {
    id: "2207",
    name: "Grundy's Game",
    link: "https://cses.fi/problemset/task/2207",
    acceptedCount: 1404,
    submissionCount: 1841,
    difficulty: 2,
  },
  {
    id: "2426",
    name: "Programmers and Artists",
    link: "https://cses.fi/problemset/task/2426",
    acceptedCount: 427,
    submissionCount: 559,
    difficulty: 2,
  },
  {
    id: "1625",
    name: "Grid Paths",
    link: "https://cses.fi/problemset/task/1625",
    acceptedCount: 8340,
    submissionCount: 10882,
    difficulty: 2,
  },
  {
    id: "2217",
    name: "Collecting Numbers II",
    link: "https://cses.fi/problemset/task/2217",
    acceptedCount: 10662,
    submissionCount: 13907,
    difficulty: 2,
  },
  {
    id: "2192",
    name: "Point in Polygon",
    link: "https://cses.fi/problemset/task/2192",
    acceptedCount: 2244,
    submissionCount: 2926,
    difficulty: 2,
  },
  {
    id: "1752",
    name: "Creating Offices",
    link: "https://cses.fi/problemset/task/1752",
    acceptedCount: 337,
    submissionCount: 439,
    difficulty: 2,
  },
  {
    id: "2109",
    name: "Substring Order II",
    link: "https://cses.fi/problemset/task/2109",
    acceptedCount: 632,
    submissionCount: 821,
    difficulty: 2,
  },
  {
    id: "1144",
    name: "Salary Queries",
    link: "https://cses.fi/problemset/task/1144",
    acceptedCount: 7115,
    submissionCount: 9202,
    difficulty: 2,
  },
  {
    id: "1680",
    name: "Longest Flight Route",
    link: "https://cses.fi/problemset/task/1680",
    acceptedCount: 11445,
    submissionCount: 14776,
    difficulty: 2,
  },
  {
    id: "2190",
    name: "Line Segment Intersection",
    link: "https://cses.fi/problemset/task/2190",
    acceptedCount: 3575,
    submissionCount: 4580,
    difficulty: 2,
  },
  {
    id: "1653",
    name: "Elevator Rides",
    link: "https://cses.fi/problemset/task/1653",
    acceptedCount: 9919,
    submissionCount: 12683,
    difficulty: 2,
  },
  {
    id: "1670",
    name: "Swap Game",
    link: "https://cses.fi/problemset/task/1670",
    acceptedCount: 1728,
    submissionCount: 2205,
    difficulty: 2,
  },
  {
    id: "1734",
    name: "Distinct Values Queries",
    link: "https://cses.fi/problemset/task/1734",
    acceptedCount: 5512,
    submissionCount: 7003,
    difficulty: 2,
  },
  {
    id: "1722",
    name: "Fibonacci Numbers",
    link: "https://cses.fi/problemset/task/1722",
    acceptedCount: 5940,
    submissionCount: 7545,
    difficulty: 2,
  },
  {
    id: "1146",
    name: "Counting Bits",
    link: "https://cses.fi/problemset/task/1146",
    acceptedCount: 2992,
    submissionCount: 3789,
    difficulty: 2,
  },
  {
    id: "1160",
    name: "Planets Queries II",
    link: "https://cses.fi/problemset/task/1160",
    acceptedCount: 3060,
    submissionCount: 3870,
    difficulty: 2,
  },
  {
    id: "2103",
    name: "Counting Patterns",
    link: "https://cses.fi/problemset/task/2103",
    acceptedCount: 1428,
    submissionCount: 1804,
    difficulty: 2,
  },
  {
    id: "1197",
    name: "Cycle Finding",
    link: "https://cses.fi/problemset/task/1197",
    acceptedCount: 11397,
    submissionCount: 14390,
    difficulty: 2,
  },
  {
    id: "2415",
    name: "Functional Graph Distribution",
    link: "https://cses.fi/problemset/task/2415",
    acceptedCount: 188,
    submissionCount: 237,
    difficulty: 2,
  },
  {
    id: "2164",
    name: "Josephus Queries",
    link: "https://cses.fi/problemset/task/2164",
    acceptedCount: 3783,
    submissionCount: 4753,
    difficulty: 2,
  },
  {
    id: "1113",
    name: "String Transform",
    link: "https://cses.fi/problemset/task/1113",
    acceptedCount: 400,
    submissionCount: 502,
    difficulty: 2,
  },
  {
    id: "2419",
    name: "Xor Pyramid",
    link: "https://cses.fi/problemset/task/2419",
    acceptedCount: 1396,
    submissionCount: 1750,
    difficulty: 2,
  },
  {
    id: "1078",
    name: "Grid Paths",
    link: "https://cses.fi/problemset/task/1078",
    acceptedCount: 620,
    submissionCount: 777,
    difficulty: 2,
  },
  {
    id: "2104",
    name: "Pattern Positions",
    link: "https://cses.fi/problemset/task/2104",
    acceptedCount: 1204,
    submissionCount: 1505,
    difficulty: 2,
  },
  {
    id: "2115",
    name: "Bit Substrings",
    link: "https://cses.fi/problemset/task/2115",
    acceptedCount: 301,
    submissionCount: 376,
    difficulty: 2,
  },
  {
    id: "1148",
    name: "Maximum Building II",
    link: "https://cses.fi/problemset/task/1148",
    acceptedCount: 359,
    submissionCount: 447,
    difficulty: 2,
  },
  {
    id: "1698",
    name: "Swap Round Sorting",
    link: "https://cses.fi/problemset/task/1698",
    acceptedCount: 356,
    submissionCount: 441,
    difficulty: 2,
  },
  {
    id: "1689",
    name: "Knight's Tour",
    link: "https://cses.fi/problemset/task/1689",
    acceptedCount: 2140,
    submissionCount: 2640,
    difficulty: 2,
  },
  {
    id: "2075",
    name: "Reversal Sorting",
    link: "https://cses.fi/problemset/task/2075",
    acceptedCount: 289,
    submissionCount: 356,
    difficulty: 2,
  },
  {
    id: "1632",
    name: "Movie Festival II",
    link: "https://cses.fi/problemset/task/1632",
    acceptedCount: 9677,
    submissionCount: 11869,
    difficulty: 2,
  },
  {
    id: "1193",
    name: "Labyrinth",
    link: "https://cses.fi/problemset/task/1193",
    acceptedCount: 29398,
    submissionCount: 36045,
    difficulty: 2,
  },
  {
    id: "2101",
    name: "New Roads Queries",
    link: "https://cses.fi/problemset/task/2101",
    acceptedCount: 1775,
    submissionCount: 2168,
    difficulty: 2,
  },
  {
    id: "1080",
    name: "Empty String",
    link: "https://cses.fi/problemset/task/1080",
    acceptedCount: 1276,
    submissionCount: 1552,
    difficulty: 2,
  },
  {
    id: "1699",
    name: "Flight Route Requests",
    link: "https://cses.fi/problemset/task/1699",
    acceptedCount: 370,
    submissionCount: 449,
    difficulty: 2,
  },
  {
    id: "1712",
    name: "Exponentiation II",
    link: "https://cses.fi/problemset/task/1712",
    acceptedCount: 14448,
    submissionCount: 17508,
    difficulty: 2,
  },
  {
    id: "1747",
    name: "Pyramid Array",
    link: "https://cses.fi/problemset/task/1747",
    acceptedCount: 611,
    submissionCount: 740,
    difficulty: 2,
  },
  {
    id: "1194",
    name: "Monsters",
    link: "https://cses.fi/problemset/task/1194",
    acceptedCount: 15784,
    submissionCount: 19107,
    difficulty: 2,
  },
  {
    id: "1735",
    name: "Range Updates and Sums",
    link: "https://cses.fi/problemset/task/1735",
    acceptedCount: 4848,
    submissionCount: 5866,
    difficulty: 2,
  },
  {
    id: "1661",
    name: "Subarray Sums II",
    link: "https://cses.fi/problemset/task/1661",
    acceptedCount: 20910,
    submissionCount: 25294,
    difficulty: 2,
  },
  {
    id: "2086",
    name: "Subarray Squares",
    link: "https://cses.fi/problemset/task/2086",
    acceptedCount: 1100,
    submissionCount: 1327,
    difficulty: 2,
  },
  {
    id: "1644",
    name: "Maximum Subarray Sum II",
    link: "https://cses.fi/problemset/task/1644",
    acceptedCount: 8882,
    submissionCount: 10705,
    difficulty: 2,
  },
  {
    id: "2195",
    name: "Convex Hull",
    link: "https://cses.fi/problemset/task/2195",
    acceptedCount: 2847,
    submissionCount: 3427,
    difficulty: 2,
  },
  {
    id: "2087",
    name: "Houses and Schools",
    link: "https://cses.fi/problemset/task/2087",
    acceptedCount: 624,
    submissionCount: 750,
    difficulty: 2,
  },
  {
    id: "2105",
    name: "Distinct Substrings",
    link: "https://cses.fi/problemset/task/2105",
    acceptedCount: 1403,
    submissionCount: 1686,
    difficulty: 2,
  },
  {
    id: "1157",
    name: "Number Grid",
    link: "https://cses.fi/problemset/task/1157",
    acceptedCount: 698,
    submissionCount: 836,
    difficulty: 2,
  },
  {
    id: "1195",
    name: "Flight Discount",
    link: "https://cses.fi/problemset/task/1195",
    acceptedCount: 16145,
    submissionCount: 19329,
    difficulty: 2,
  },
  {
    id: "1709",
    name: "Coin Grid",
    link: "https://cses.fi/problemset/task/1709",
    acceptedCount: 675,
    submissionCount: 808,
    difficulty: 2,
  },
  {
    id: "1750",
    name: "Planets Queries I",
    link: "https://cses.fi/problemset/task/1750",
    acceptedCount: 8428,
    submissionCount: 10041,
    difficulty: 2,
  },
  {
    id: "1189",
    name: "Food Division",
    link: "https://cses.fi/problemset/task/1189",
    acceptedCount: 452,
    submissionCount: 538,
    difficulty: 2,
  },
  {
    id: "2143",
    name: "Reachability Queries",
    link: "https://cses.fi/problemset/task/2143",
    acceptedCount: 1312,
    submissionCount: 1561,
    difficulty: 2,
  },
  {
    id: "2185",
    name: "Prime Multiples",
    link: "https://cses.fi/problemset/task/2185",
    acceptedCount: 5053,
    submissionCount: 5997,
    difficulty: 2,
  },
  {
    id: "2431",
    name: "Digit Queries",
    link: "https://cses.fi/problemset/task/2431",
    acceptedCount: 14720,
    submissionCount: 17425,
    difficulty: 1,
  },
  {
    id: "2417",
    name: "Counting Coprime Pairs",
    link: "https://cses.fi/problemset/task/2417",
    acceptedCount: 3261,
    submissionCount: 3860,
    difficulty: 1,
  },
  {
    id: "2169",
    name: "Nested Ranges Count",
    link: "https://cses.fi/problemset/task/2169",
    acceptedCount: 6088,
    submissionCount: 7200,
    difficulty: 1,
  },
  {
    id: "1161",
    name: "Stick Divisions",
    link: "https://cses.fi/problemset/task/1161",
    acceptedCount: 3246,
    submissionCount: 3835,
    difficulty: 1,
  },
  {
    id: "1736",
    name: "Polynomial Queries",
    link: "https://cses.fi/problemset/task/1736",
    acceptedCount: 3608,
    submissionCount: 4261,
    difficulty: 1,
  },
  {
    id: "2425",
    name: "Stack Weights",
    link: "https://cses.fi/problemset/task/2425",
    acceptedCount: 489,
    submissionCount: 577,
    difficulty: 1,
  },
  {
    id: "2420",
    name: "Palindrome Queries",
    link: "https://cses.fi/problemset/task/2420",
    acceptedCount: 1701,
    submissionCount: 2003,
    difficulty: 1,
  },
  {
    id: "1130",
    name: "Tree Matching",
    link: "https://cses.fi/problemset/task/1130",
    acceptedCount: 13874,
    submissionCount: 16331,
    difficulty: 1,
  },
  {
    id: "1091",
    name: "Concert Tickets",
    link: "https://cses.fi/problemset/task/1091",
    acceptedCount: 35536,
    submissionCount: 41817,
    difficulty: 1,
  },
  {
    id: "2179",
    name: "Even Outdegree Edges",
    link: "https://cses.fi/problemset/task/2179",
    acceptedCount: 1089,
    submissionCount: 1280,
    difficulty: 1,
  },
  {
    id: "1081",
    name: "Common Divisors",
    link: "https://cses.fi/problemset/task/1081",
    acceptedCount: 12077,
    submissionCount: 14192,
    difficulty: 1,
  },
  {
    id: "1693",
    name: "Teleporters Path",
    link: "https://cses.fi/problemset/task/1693",
    acceptedCount: 3781,
    submissionCount: 4435,
    difficulty: 1,
  },
  {
    id: "2168",
    name: "Nested Ranges Check",
    link: "https://cses.fi/problemset/task/2168",
    acceptedCount: 8831,
    submissionCount: 10318,
    difficulty: 1,
  },
  {
    id: "2130",
    name: "Distinct Routes II",
    link: "https://cses.fi/problemset/task/2130",
    acceptedCount: 465,
    submissionCount: 540,
    difficulty: 1,
  },
  {
    id: "1697",
    name: "Chess Tournament",
    link: "https://cses.fi/problemset/task/1697",
    acceptedCount: 919,
    submissionCount: 1067,
    difficulty: 1,
  },
  {
    id: "1159",
    name: "Book Shop II",
    link: "https://cses.fi/problemset/task/1159",
    acceptedCount: 932,
    submissionCount: 1082,
    difficulty: 1,
  },
  {
    id: "1164",
    name: "Room Allocation",
    link: "https://cses.fi/problemset/task/1164",
    acceptedCount: 15657,
    submissionCount: 18156,
    difficulty: 1,
  },
  {
    id: "2187",
    name: "Bracket Sequences II",
    link: "https://cses.fi/problemset/task/2187",
    acceptedCount: 1930,
    submissionCount: 2234,
    difficulty: 1,
  },
  {
    id: "1700",
    name: "Tree Isomorphism I",
    link: "https://cses.fi/problemset/task/1700",
    acceptedCount: 917,
    submissionCount: 1061,
    difficulty: 1,
  },
  {
    id: "2416",
    name: "Increasing Array Queries",
    link: "https://cses.fi/problemset/task/2416",
    acceptedCount: 2145,
    submissionCount: 2480,
    difficulty: 1,
  },
  {
    id: "1077",
    name: "Sliding Window Cost",
    link: "https://cses.fi/problemset/task/1077",
    acceptedCount: 7977,
    submissionCount: 9220,
    difficulty: 1,
  },
  {
    id: "1141",
    name: "Playlist",
    link: "https://cses.fi/problemset/task/1141",
    acceptedCount: 26726,
    submissionCount: 30889,
    difficulty: 1,
  },
  {
    id: "2132",
    name: "Increasing Array II",
    link: "https://cses.fi/problemset/task/2132",
    acceptedCount: 671,
    submissionCount: 775,
    difficulty: 1,
  },
  {
    id: "1707",
    name: "Graph Girth",
    link: "https://cses.fi/problemset/task/1707",
    acceptedCount: 2658,
    submissionCount: 3068,
    difficulty: 1,
  },
  {
    id: "1188",
    name: "Bit Inversions",
    link: "https://cses.fi/problemset/task/1188",
    acceptedCount: 1973,
    submissionCount: 2268,
    difficulty: 1,
  },
  {
    id: "1701",
    name: "Tree Isomorphism II",
    link: "https://cses.fi/problemset/task/1701",
    acceptedCount: 724,
    submissionCount: 832,
    difficulty: 1,
  },
  {
    id: "2220",
    name: "Counting Numbers",
    link: "https://cses.fi/problemset/task/2220",
    acceptedCount: 7739,
    submissionCount: 8867,
    difficulty: 1,
  },
  {
    id: "1076",
    name: "Sliding Window Median",
    link: "https://cses.fi/problemset/task/1076",
    acceptedCount: 11934,
    submissionCount: 13659,
    difficulty: 1,
  },
  {
    id: "1690",
    name: "Hamiltonian Flights",
    link: "https://cses.fi/problemset/task/1690",
    acceptedCount: 5709,
    submissionCount: 6532,
    difficulty: 1,
  },
  {
    id: "2088",
    name: "Knuth Division",
    link: "https://cses.fi/problemset/task/2088",
    acceptedCount: 743,
    submissionCount: 850,
    difficulty: 1,
  },
  {
    id: "1636",
    name: "Coin Combinations II",
    link: "https://cses.fi/problemset/task/1636",
    acceptedCount: 42254,
    submissionCount: 48268,
    difficulty: 1,
  },
  {
    id: "1191",
    name: "Cyclic Array",
    link: "https://cses.fi/problemset/task/1191",
    acceptedCount: 943,
    submissionCount: 1077,
    difficulty: 1,
  },
  {
    id: "1075",
    name: "Permutations II",
    link: "https://cses.fi/problemset/task/1075",
    acceptedCount: 730,
    submissionCount: 832,
    difficulty: 1,
  },
  {
    id: "1678",
    name: "Round Trip II",
    link: "https://cses.fi/problemset/task/1678",
    acceptedCount: 12882,
    submissionCount: 14680,
    difficulty: 1,
  },
  {
    id: "1733",
    name: "Finding Periods",
    link: "https://cses.fi/problemset/task/1733",
    acceptedCount: 4819,
    submissionCount: 5488,
    difficulty: 1,
  },
  {
    id: "1672",
    name: "Shortest Routes II",
    link: "https://cses.fi/problemset/task/1672",
    acceptedCount: 21098,
    submissionCount: 24017,
    difficulty: 1,
  },
  {
    id: "1623",
    name: "Apple Division",
    link: "https://cses.fi/problemset/task/1623",
    acceptedCount: 34570,
    submissionCount: 39320,
    difficulty: 1,
  },
  {
    id: "2108",
    name: "Substring Order I",
    link: "https://cses.fi/problemset/task/2108",
    acceptedCount: 961,
    submissionCount: 1093,
    difficulty: 1,
  },
  {
    id: "2133",
    name: "Dynamic Connectivity",
    link: "https://cses.fi/problemset/task/2133",
    acceptedCount: 813,
    submissionCount: 924,
    difficulty: 1,
  },
  {
    id: "1713",
    name: "Counting Divisors",
    link: "https://cses.fi/problemset/task/1713",
    acceptedCount: 18289,
    submissionCount: 20772,
    difficulty: 1,
  },
  {
    id: "2176",
    name: "Counting Bishops",
    link: "https://cses.fi/problemset/task/2176",
    acceptedCount: 297,
    submissionCount: 337,
    difficulty: 1,
  },
  {
    id: "2205",
    name: "Gray Code",
    link: "https://cses.fi/problemset/task/2205",
    acceptedCount: 26683,
    submissionCount: 30263,
    difficulty: 1,
  },
  {
    id: "2121",
    name: "Parcel Delivery",
    link: "https://cses.fi/problemset/task/2121",
    acceptedCount: 601,
    submissionCount: 681,
    difficulty: 1,
  },
  {
    id: "1695",
    name: "Police Chase",
    link: "https://cses.fi/problemset/task/1695",
    acceptedCount: 3090,
    submissionCount: 3500,
    difficulty: 1,
  },
  {
    id: "2215",
    name: "Monotone Subsequences",
    link: "https://cses.fi/problemset/task/2215",
    acceptedCount: 576,
    submissionCount: 652,
    difficulty: 1,
  },
  {
    id: "1640",
    name: "Sum of Two Values",
    link: "https://cses.fi/problemset/task/1640",
    acceptedCount: 40544,
    submissionCount: 45830,
    difficulty: 1,
  },
  {
    id: "1145",
    name: "Increasing Subsequence",
    link: "https://cses.fi/problemset/task/1145",
    acceptedCount: 23523,
    submissionCount: 26589,
    difficulty: 1,
  },
  {
    id: "1140",
    name: "Projects",
    link: "https://cses.fi/problemset/task/1140",
    acceptedCount: 15967,
    submissionCount: 18035,
    difficulty: 1,
  },
  {
    id: "1163",
    name: "Traffic Lights",
    link: "https://cses.fi/problemset/task/1163",
    acceptedCount: 21097,
    submissionCount: 23799,
    difficulty: 1,
  },
  {
    id: "2428",
    name: "Subarray Distinct Values",
    link: "https://cses.fi/problemset/task/2428",
    acceptedCount: 11169,
    submissionCount: 12588,
    difficulty: 1,
  },
  {
    id: "1751",
    name: "Planets Cycles",
    link: "https://cses.fi/problemset/task/1751",
    acceptedCount: 5258,
    submissionCount: 5926,
    difficulty: 1,
  },
  {
    id: "1741",
    name: "Area of Rectangles",
    link: "https://cses.fi/problemset/task/1741",
    acceptedCount: 902,
    submissionCount: 1016,
    difficulty: 1,
  },
  {
    id: "2189",
    name: "Point Location Test",
    link: "https://cses.fi/problemset/task/2189",
    acceptedCount: 5995,
    submissionCount: 6751,
    difficulty: 1,
  },
  {
    id: "1686",
    name: "Coin Collector",
    link: "https://cses.fi/problemset/task/1686",
    acceptedCount: 5898,
    submissionCount: 6641,
    difficulty: 1,
  },
  {
    id: "1642",
    name: "Sum of Four Values",
    link: "https://cses.fi/problemset/task/1642",
    acceptedCount: 13345,
    submissionCount: 15019,
    difficulty: 1,
  },
  {
    id: "2106",
    name: "Repeating Substring",
    link: "https://cses.fi/problemset/task/2106",
    acceptedCount: 1568,
    submissionCount: 1764,
    difficulty: 1,
  },
  {
    id: "1664",
    name: "Movie Festival Queries",
    link: "https://cses.fi/problemset/task/1664",
    acceptedCount: 833,
    submissionCount: 937,
    difficulty: 1,
  },
  {
    id: "2422",
    name: "Multiplication Table",
    link: "https://cses.fi/problemset/task/2422",
    acceptedCount: 5177,
    submissionCount: 5820,
    difficulty: 1,
  },
  {
    id: "1196",
    name: "Flight Routes",
    link: "https://cses.fi/problemset/task/1196",
    acceptedCount: 11017,
    submissionCount: 12381,
    difficulty: 1,
  },
  {
    id: "1746",
    name: "Array Description",
    link: "https://cses.fi/problemset/task/1746",
    acceptedCount: 28591,
    submissionCount: 32090,
    difficulty: 1,
  },
  {
    id: "1671",
    name: "Shortest Routes I",
    link: "https://cses.fi/problemset/task/1671",
    acceptedCount: 26129,
    submissionCount: 29317,
    difficulty: 1,
  },
  {
    id: "1079",
    name: "Binomial Coefficients",
    link: "https://cses.fi/problemset/task/1079",
    acceptedCount: 8345,
    submissionCount: 9362,
    difficulty: 1,
  },
  {
    id: "2072",
    name: "Cut and Paste",
    link: "https://cses.fi/problemset/task/2072",
    acceptedCount: 1275,
    submissionCount: 1430,
    difficulty: 1,
  },
  {
    id: "1702",
    name: "Tree Traversals",
    link: "https://cses.fi/problemset/task/1702",
    acceptedCount: 903,
    submissionCount: 1012,
    difficulty: 1,
  },
  {
    id: "1084",
    name: "Apartments",
    link: "https://cses.fi/problemset/task/1084",
    acceptedCount: 46039,
    submissionCount: 51592,
    difficulty: 1,
  },
  {
    id: "2137",
    name: "Beautiful Subgrids",
    link: "https://cses.fi/problemset/task/2137",
    acceptedCount: 1971,
    submissionCount: 2207,
    difficulty: 1,
  },
  {
    id: "2131",
    name: "Grid Puzzle II",
    link: "https://cses.fi/problemset/task/2131",
    acceptedCount: 363,
    submissionCount: 406,
    difficulty: 1,
  },
  {
    id: "1641",
    name: "Sum of Three Values",
    link: "https://cses.fi/problemset/task/1641",
    acceptedCount: 21513,
    submissionCount: 24059,
    difficulty: 1,
  },
  {
    id: "2162",
    name: "Josephus Problem I",
    link: "https://cses.fi/problemset/task/2162",
    acceptedCount: 15741,
    submissionCount: 17562,
    difficulty: 1,
  },
  {
    id: "1139",
    name: "Distinct Colors",
    link: "https://cses.fi/problemset/task/1139",
    acceptedCount: 6779,
    submissionCount: 7561,
    difficulty: 1,
  },
  {
    id: "1684",
    name: "Giant Pizza",
    link: "https://cses.fi/problemset/task/1684",
    acceptedCount: 3830,
    submissionCount: 4259,
    difficulty: 1,
  },
  {
    id: "2084",
    name: "Monster Game I",
    link: "https://cses.fi/problemset/task/2084",
    acceptedCount: 988,
    submissionCount: 1098,
    difficulty: 1,
  },
  {
    id: "2112",
    name: "One Bit Positions",
    link: "https://cses.fi/problemset/task/2112",
    acceptedCount: 667,
    submissionCount: 741,
    difficulty: 1,
  },
  {
    id: "2432",
    name: "Grid Puzzle I",
    link: "https://cses.fi/problemset/task/2432",
    acceptedCount: 427,
    submissionCount: 474,
    difficulty: 1,
  },
  {
    id: "1158",
    name: "Book Shop",
    link: "https://cses.fi/problemset/task/1158",
    acceptedCount: 39322,
    submissionCount: 43647,
    difficulty: 1,
  },
  {
    id: "1743",
    name: "String Reorder",
    link: "https://cses.fi/problemset/task/1743",
    acceptedCount: 629,
    submissionCount: 698,
    difficulty: 1,
  },
  {
    id: "1097",
    name: "Removal Game",
    link: "https://cses.fi/problemset/task/1097",
    acceptedCount: 21054,
    submissionCount: 23241,
    difficulty: 1,
  },
  {
    id: "1691",
    name: "Mail Delivery",
    link: "https://cses.fi/problemset/task/1691",
    acceptedCount: 5052,
    submissionCount: 5574,
    difficulty: 1,
  },
  {
    id: "2111",
    name: "Apples and Bananas",
    link: "https://cses.fi/problemset/task/2111",
    acceptedCount: 784,
    submissionCount: 865,
    difficulty: 1,
  },
  {
    id: "1732",
    name: "Finding Borders",
    link: "https://cses.fi/problemset/task/1732",
    acceptedCount: 6797,
    submissionCount: 7497,
    difficulty: 1,
  },
  {
    id: "2229",
    name: "Permutation Inversions",
    link: "https://cses.fi/problemset/task/2229",
    acceptedCount: 842,
    submissionCount: 928,
    difficulty: 1,
  },
  {
    id: "1620",
    name: "Factory Machines",
    link: "https://cses.fi/problemset/task/1620",
    acceptedCount: 22035,
    submissionCount: 24281,
    difficulty: 1,
  },
  {
    id: "2181",
    name: "Counting Tilings",
    link: "https://cses.fi/problemset/task/2181",
    acceptedCount: 5738,
    submissionCount: 6318,
    difficulty: 1,
  },
  {
    id: "1669",
    name: "Round Trip",
    link: "https://cses.fi/problemset/task/1669",
    acceptedCount: 24029,
    submissionCount: 26445,
    difficulty: 1,
  },
  {
    id: "2064",
    name: "Bracket Sequences I",
    link: "https://cses.fi/problemset/task/2064",
    acceptedCount: 3740,
    submissionCount: 4114,
    difficulty: 1,
  },
  {
    id: "1754",
    name: "Coin Piles",
    link: "https://cses.fi/problemset/task/1754",
    acceptedCount: 44215,
    submissionCount: 48631,
    difficulty: 1,
  },
  {
    id: "2073",
    name: "Substring Reversals",
    link: "https://cses.fi/problemset/task/2073",
    acceptedCount: 1116,
    submissionCount: 1227,
    difficulty: 1,
  },
  {
    id: "1662",
    name: "Subarray Divisibility",
    link: "https://cses.fi/problemset/task/1662",
    acceptedCount: 19451,
    submissionCount: 21379,
    difficulty: 1,
  },
  {
    id: "2186",
    name: "Special Substrings",
    link: "https://cses.fi/problemset/task/2186",
    acceptedCount: 826,
    submissionCount: 907,
    difficulty: 1,
  },
  {
    id: "2177",
    name: "Strongly Connected Edges",
    link: "https://cses.fi/problemset/task/2177",
    acceptedCount: 1220,
    submissionCount: 1339,
    difficulty: 1,
  },
  {
    id: "1190",
    name: "Subarray Sum Queries",
    link: "https://cses.fi/problemset/task/1190",
    acceptedCount: 6221,
    submissionCount: 6816,
    difficulty: 1,
  },
  {
    id: "1744",
    name: "Rectangle Cutting",
    link: "https://cses.fi/problemset/task/1744",
    acceptedCount: 24244,
    submissionCount: 26562,
    difficulty: 1,
  },
  {
    id: "1655",
    name: "Maximum Xor Subarray",
    link: "https://cses.fi/problemset/task/1655",
    acceptedCount: 1926,
    submissionCount: 2109,
    difficulty: 1,
  },
  {
    id: "2209",
    name: "Counting Necklaces",
    link: "https://cses.fi/problemset/task/2209",
    acceptedCount: 1770,
    submissionCount: 1938,
    difficulty: 1,
  },
  {
    id: "2110",
    name: "Substring Distribution",
    link: "https://cses.fi/problemset/task/2110",
    acceptedCount: 892,
    submissionCount: 976,
    difficulty: 1,
  },
  {
    id: "1682",
    name: "Flight Routes Check",
    link: "https://cses.fi/problemset/task/1682",
    acceptedCount: 11660,
    submissionCount: 12758,
    difficulty: 1,
  },
  {
    id: "1099",
    name: "Stair Game",
    link: "https://cses.fi/problemset/task/1099",
    acceptedCount: 2110,
    submissionCount: 2308,
    difficulty: 1,
  },
  {
    id: "2166",
    name: "Prefix Sum Queries",
    link: "https://cses.fi/problemset/task/2166",
    acceptedCount: 6145,
    submissionCount: 6718,
    difficulty: 1,
  },
  {
    id: "1134",
    name: "Prüfer Code",
    link: "https://cses.fi/problemset/task/1134",
    acceptedCount: 1186,
    submissionCount: 1296,
    difficulty: 1,
  },
  {
    id: "1071",
    name: "Number Spiral",
    link: "https://cses.fi/problemset/task/1071",
    acceptedCount: 56478,
    submissionCount: 61714,
    difficulty: 1,
  },
  {
    id: "1096",
    name: "Throwing Dice",
    link: "https://cses.fi/problemset/task/1096",
    acceptedCount: 3097,
    submissionCount: 3382,
    difficulty: 1,
  },
  {
    id: "2113",
    name: "Signal Processing",
    link: "https://cses.fi/problemset/task/2113",
    acceptedCount: 622,
    submissionCount: 677,
    difficulty: 1,
  },
  {
    id: "2136",
    name: "Hamming Distance",
    link: "https://cses.fi/problemset/task/2136",
    acceptedCount: 2766,
    submissionCount: 3010,
    difficulty: 1,
  },
  {
    id: "1086",
    name: "Writing Numbers",
    link: "https://cses.fi/problemset/task/1086",
    acceptedCount: 635,
    submissionCount: 691,
    difficulty: 1,
  },
  {
    id: "1635",
    name: "Coin Combinations I",
    link: "https://cses.fi/problemset/task/1635",
    acceptedCount: 50222,
    submissionCount: 54631,
    difficulty: 1,
  },
  {
    id: "2074",
    name: "Reversals and Sums",
    link: "https://cses.fi/problemset/task/2074",
    acceptedCount: 1122,
    submissionCount: 1220,
    difficulty: 1,
  },
  {
    id: "1681",
    name: "Game Routes",
    link: "https://cses.fi/problemset/task/1681",
    acceptedCount: 13126,
    submissionCount: 14261,
    difficulty: 1,
  },
  {
    id: "1093",
    name: "Two Sets II",
    link: "https://cses.fi/problemset/task/1093",
    acceptedCount: 22890,
    submissionCount: 24859,
    difficulty: 1,
  },
  {
    id: "1621",
    name: "Distinct Numbers",
    link: "https://cses.fi/problemset/task/1621",
    acceptedCount: 62774,
    submissionCount: 68162,
    difficulty: 1,
  },
  {
    id: "2085",
    name: "Monster Game II",
    link: "https://cses.fi/problemset/task/2085",
    acceptedCount: 869,
    submissionCount: 943,
    difficulty: 1,
  },
  {
    id: "2208",
    name: "Another Game",
    link: "https://cses.fi/problemset/task/2208",
    acceptedCount: 1611,
    submissionCount: 1748,
    difficulty: 1,
  },
  {
    id: "1619",
    name: "Restaurant Customers",
    link: "https://cses.fi/problemset/task/1619",
    acceptedCount: 36333,
    submissionCount: 39415,
    difficulty: 1,
  },
  {
    id: "1090",
    name: "Ferris Wheel",
    link: "https://cses.fi/problemset/task/1090",
    acceptedCount: 44091,
    submissionCount: 47828,
    difficulty: 1,
  },
  {
    id: "1202",
    name: "Investigation",
    link: "https://cses.fi/problemset/task/1202",
    acceptedCount: 9663,
    submissionCount: 10469,
    difficulty: 1,
  },
  {
    id: "2228",
    name: "Counting Sequences",
    link: "https://cses.fi/problemset/task/2228",
    acceptedCount: 506,
    submissionCount: 548,
    difficulty: 1,
  },
  {
    id: "2138",
    name: "Reachable Nodes",
    link: "https://cses.fi/problemset/task/2138",
    acceptedCount: 1943,
    submissionCount: 2104,
    difficulty: 1,
  },
  {
    id: "1739",
    name: "Forest Queries II",
    link: "https://cses.fi/problemset/task/1739",
    acceptedCount: 3779,
    submissionCount: 4091,
    difficulty: 1,
  },
  {
    id: "1092",
    name: "Two Sets",
    link: "https://cses.fi/problemset/task/1092",
    acceptedCount: 46423,
    submissionCount: 50238,
    difficulty: 1,
  },
  {
    id: "1717",
    name: "Christmas Party",
    link: "https://cses.fi/problemset/task/1717",
    acceptedCount: 5333,
    submissionCount: 5770,
    difficulty: 1,
  },
  {
    id: "1132",
    name: "Tree Distances I",
    link: "https://cses.fi/problemset/task/1132",
    acceptedCount: 15193,
    submissionCount: 16433,
    difficulty: 1,
  },
  {
    id: "1737",
    name: "Range Queries and Copies",
    link: "https://cses.fi/problemset/task/1737",
    acceptedCount: 2550,
    submissionCount: 2758,
    difficulty: 0,
  },
  {
    id: "1740",
    name: "Intersection Points",
    link: "https://cses.fi/problemset/task/1740",
    acceptedCount: 1557,
    submissionCount: 1684,
    difficulty: 0,
  },
  {
    id: "1725",
    name: "Dice Probability",
    link: "https://cses.fi/problemset/task/1725",
    acceptedCount: 2658,
    submissionCount: 2873,
    difficulty: 0,
  },
  {
    id: "1716",
    name: "Distributing Apples",
    link: "https://cses.fi/problemset/task/1716",
    acceptedCount: 6888,
    submissionCount: 7445,
    difficulty: 0,
  },
  {
    id: "1634",
    name: "Minimizing Coins",
    link: "https://cses.fi/problemset/task/1634",
    acceptedCount: 55020,
    submissionCount: 59363,
    difficulty: 0,
  },
  {
    id: "2210",
    name: "Counting Grids",
    link: "https://cses.fi/problemset/task/2210",
    acceptedCount: 1426,
    submissionCount: 1538,
    difficulty: 0,
  },
  {
    id: "1651",
    name: "Range Update Queries",
    link: "https://cses.fi/problemset/task/1651",
    acceptedCount: 16502,
    submissionCount: 17792,
    difficulty: 0,
  },
  {
    id: "1149",
    name: "String Removals",
    link: "https://cses.fi/problemset/task/1149",
    acceptedCount: 809,
    submissionCount: 872,
    difficulty: 0,
  },
  {
    id: "2216",
    name: "Collecting Numbers",
    link: "https://cses.fi/problemset/task/2216",
    acceptedCount: 26541,
    submissionCount: 28604,
    difficulty: 0,
  },
  {
    id: "1723",
    name: "Graph Paths I",
    link: "https://cses.fi/problemset/task/1723",
    acceptedCount: 2896,
    submissionCount: 3118,
    difficulty: 0,
  },
  {
    id: "1135",
    name: "Distance Queries",
    link: "https://cses.fi/problemset/task/1135",
    acceptedCount: 11849,
    submissionCount: 12755,
    difficulty: 0,
  },
  {
    id: "1073",
    name: "Towers",
    link: "https://cses.fi/problemset/task/1073",
    acceptedCount: 27325,
    submissionCount: 29410,
    difficulty: 0,
  },
  {
    id: "1660",
    name: "Subarray Sums I",
    link: "https://cses.fi/problemset/task/1660",
    acceptedCount: 23390,
    submissionCount: 25149,
    difficulty: 0,
  },
  {
    id: "1674",
    name: "Subordinates",
    link: "https://cses.fi/problemset/task/1674",
    acceptedCount: 24911,
    submissionCount: 26768,
    difficulty: 0,
  },
  {
    id: "1748",
    name: "Increasing Subsequence II",
    link: "https://cses.fi/problemset/task/1748",
    acceptedCount: 1995,
    submissionCount: 2143,
    difficulty: 0,
  },
  {
    id: "1631",
    name: "Reading Books",
    link: "https://cses.fi/problemset/task/1631",
    acceptedCount: 14560,
    submissionCount: 15639,
    difficulty: 0,
  },
  {
    id: "1162",
    name: "Sorting Methods",
    link: "https://cses.fi/problemset/task/1162",
    acceptedCount: 679,
    submissionCount: 729,
    difficulty: 0,
  },
  {
    id: "1095",
    name: "Exponentiation",
    link: "https://cses.fi/problemset/task/1095",
    acceptedCount: 20204,
    submissionCount: 21683,
    difficulty: 0,
  },
  {
    id: "1654",
    name: "Bit Problem",
    link: "https://cses.fi/problemset/task/1654",
    acceptedCount: 1453,
    submissionCount: 1559,
    difficulty: 0,
  },
  {
    id: "1647",
    name: "Static Range Minimum Queries",
    link: "https://cses.fi/problemset/task/1647",
    acceptedCount: 21507,
    submissionCount: 23069,
    difficulty: 0,
  },
  {
    id: "2129",
    name: "Task Assignment",
    link: "https://cses.fi/problemset/task/2129",
    acceptedCount: 684,
    submissionCount: 733,
    difficulty: 0,
  },
  {
    id: "1143",
    name: "Hotel Queries",
    link: "https://cses.fi/problemset/task/1143",
    acceptedCount: 11818,
    submissionCount: 12652,
    difficulty: 0,
  },
  {
    id: "1137",
    name: "Subtree Queries",
    link: "https://cses.fi/problemset/task/1137",
    acceptedCount: 8944,
    submissionCount: 9573,
    difficulty: 0,
  },
  {
    id: "1136",
    name: "Counting Paths",
    link: "https://cses.fi/problemset/task/1136",
    acceptedCount: 7240,
    submissionCount: 7742,
    difficulty: 0,
  },
  {
    id: "1679",
    name: "Course Schedule",
    link: "https://cses.fi/problemset/task/1679",
    acceptedCount: 17144,
    submissionCount: 18332,
    difficulty: 0,
  },
  {
    id: "1618",
    name: "Trailing Zeros",
    link: "https://cses.fi/problemset/task/1618",
    acceptedCount: 50092,
    submissionCount: 53447,
    difficulty: 0,
  },
  {
    id: "2191",
    name: "Polygon Area",
    link: "https://cses.fi/problemset/task/2191",
    acceptedCount: 4208,
    submissionCount: 4487,
    difficulty: 0,
  },
  {
    id: "1706",
    name: "School Excursion",
    link: "https://cses.fi/problemset/task/1706",
    acceptedCount: 1136,
    submissionCount: 1211,
    difficulty: 0,
  },
  {
    id: "1726",
    name: "Moving Robots",
    link: "https://cses.fi/problemset/task/1726",
    acceptedCount: 1352,
    submissionCount: 1441,
    difficulty: 0,
  },
  {
    id: "1131",
    name: "Tree Diameter",
    link: "https://cses.fi/problemset/task/1131",
    acceptedCount: 20359,
    submissionCount: 21699,
    difficulty: 0,
  },
  {
    id: "1696",
    name: "School Dance",
    link: "https://cses.fi/problemset/task/1696",
    acceptedCount: 3405,
    submissionCount: 3629,
    difficulty: 0,
  },
  {
    id: "1677",
    name: "Network Breakdown",
    link: "https://cses.fi/problemset/task/1677",
    acceptedCount: 769,
    submissionCount: 818,
    difficulty: 0,
  },
  {
    id: "1715",
    name: "Creating Strings II",
    link: "https://cses.fi/problemset/task/1715",
    acceptedCount: 7115,
    submissionCount: 7568,
    difficulty: 0,
  },
  {
    id: "1629",
    name: "Movie Festival",
    link: "https://cses.fi/problemset/task/1629",
    acceptedCount: 34407,
    submissionCount: 36595,
    difficulty: 0,
  },
  {
    id: "1756",
    name: "Acyclic Graph Edges",
    link: "https://cses.fi/problemset/task/1756",
    acceptedCount: 1809,
    submissionCount: 1924,
    difficulty: 0,
  },
  {
    id: "1668",
    name: "Building Teams",
    link: "https://cses.fi/problemset/task/1668",
    acceptedCount: 30483,
    submissionCount: 32417,
    difficulty: 0,
  },
  {
    id: "1633",
    name: "Dice Combinations",
    link: "https://cses.fi/problemset/task/1633",
    acceptedCount: 63809,
    submissionCount: 67793,
    difficulty: 0,
  },
  {
    id: "1142",
    name: "Advertisement",
    link: "https://cses.fi/problemset/task/1142",
    acceptedCount: 3560,
    submissionCount: 3780,
    difficulty: 0,
  },
  {
    id: "2413",
    name: "Counting Towers",
    link: "https://cses.fi/problemset/task/2413",
    acceptedCount: 17001,
    submissionCount: 18051,
    difficulty: 0,
  },
  {
    id: "1138",
    name: "Path Queries",
    link: "https://cses.fi/problemset/task/1138",
    acceptedCount: 7132,
    submissionCount: 7565,
    difficulty: 0,
  },
  {
    id: "1639",
    name: "Edit Distance",
    link: "https://cses.fi/problemset/task/1639",
    acceptedCount: 29160,
    submissionCount: 30914,
    difficulty: 0,
  },
  {
    id: "1749",
    name: "List Removals",
    link: "https://cses.fi/problemset/task/1749",
    acceptedCount: 9860,
    submissionCount: 10445,
    difficulty: 0,
  },
  {
    id: "2078",
    name: "Eulerian Subgraphs",
    link: "https://cses.fi/problemset/task/2078",
    acceptedCount: 679,
    submissionCount: 719,
    difficulty: 0,
  },
  {
    id: "1755",
    name: "Palindrome Reorder",
    link: "https://cses.fi/problemset/task/1755",
    acceptedCount: 40963,
    submissionCount: 43375,
    difficulty: 0,
  },
  {
    id: "1687",
    name: "Company Queries I",
    link: "https://cses.fi/problemset/task/1687",
    acceptedCount: 13812,
    submissionCount: 14602,
    difficulty: 0,
  },
  {
    id: "1617",
    name: "Bit Strings",
    link: "https://cses.fi/problemset/task/1617",
    acceptedCount: 53543,
    submissionCount: 56599,
    difficulty: 0,
  },
  {
    id: "1085",
    name: "Array Division",
    link: "https://cses.fi/problemset/task/1085",
    acceptedCount: 18358,
    submissionCount: 19401,
    difficulty: 0,
  },
  {
    id: "1192",
    name: "Counting Rooms",
    link: "https://cses.fi/problemset/task/1192",
    acceptedCount: 43665,
    submissionCount: 46145,
    difficulty: 0,
  },
  {
    id: "2214",
    name: "Inverse Inversions",
    link: "https://cses.fi/problemset/task/2214",
    acceptedCount: 860,
    submissionCount: 905,
    difficulty: 0,
  },
  {
    id: "1688",
    name: "Company Queries II",
    link: "https://cses.fi/problemset/task/1688",
    acceptedCount: 12945,
    submissionCount: 13621,
    difficulty: 0,
  },
  {
    id: "1083",
    name: "Missing Number",
    link: "https://cses.fi/problemset/task/1083",
    acceptedCount: 111243,
    submissionCount: 116980,
    difficulty: 0,
  },
  {
    id: "2107",
    name: "String Functions",
    link: "https://cses.fi/problemset/task/2107",
    acceptedCount: 1350,
    submissionCount: 1419,
    difficulty: 0,
  },
  {
    id: "1074",
    name: "Stick Lengths",
    link: "https://cses.fi/problemset/task/1074",
    acceptedCount: 35233,
    submissionCount: 37017,
    difficulty: 0,
  },
  {
    id: "2077",
    name: "Necessary Cities",
    link: "https://cses.fi/problemset/task/2077",
    acceptedCount: 1524,
    submissionCount: 1601,
    difficulty: 0,
  },
  {
    id: "1692",
    name: "De Bruijn Sequence",
    link: "https://cses.fi/problemset/task/1692",
    acceptedCount: 2653,
    submissionCount: 2785,
    difficulty: 0,
  },
  {
    id: "1724",
    name: "Graph Paths II",
    link: "https://cses.fi/problemset/task/1724",
    acceptedCount: 2412,
    submissionCount: 2530,
    difficulty: 0,
  },
  {
    id: "1068",
    name: "Weird Algorithm",
    link: "https://cses.fi/problemset/task/1068",
    acceptedCount: 129421,
    submissionCount: 135599,
    difficulty: 0,
  },
  {
    id: "1643",
    name: "Maximum Subarray Sum",
    link: "https://cses.fi/problemset/task/1643",
    acceptedCount: 39525,
    submissionCount: 41401,
    difficulty: 0,
  },
  {
    id: "1675",
    name: "Road Reparation",
    link: "https://cses.fi/problemset/task/1675",
    acceptedCount: 13028,
    submissionCount: 13633,
    difficulty: 0,
  },
  {
    id: "1147",
    name: "Maximum Building I",
    link: "https://cses.fi/problemset/task/1147",
    acceptedCount: 1778,
    submissionCount: 1860,
    difficulty: 0,
  },
  {
    id: "1646",
    name: "Static Range Sum Queries",
    link: "https://cses.fi/problemset/task/1646",
    acceptedCount: 30141,
    submissionCount: 31508,
    difficulty: 0,
  },
  {
    id: "1648",
    name: "Dynamic Range Sum Queries",
    link: "https://cses.fi/problemset/task/1648",
    acceptedCount: 22269,
    submissionCount: 23274,
    difficulty: 0,
  },
  {
    id: "1667",
    name: "Message Route",
    link: "https://cses.fi/problemset/task/1667",
    acceptedCount: 32277,
    submissionCount: 33724,
    difficulty: 0,
  },
  {
    id: "1098",
    name: "Nim Game II",
    link: "https://cses.fi/problemset/task/1098",
    acceptedCount: 3110,
    submissionCount: 3247,
    difficulty: 0,
  },
  {
    id: "1133",
    name: "Tree Distances II",
    link: "https://cses.fi/problemset/task/1133",
    acceptedCount: 12493,
    submissionCount: 13038,
    difficulty: 0,
  },
  {
    id: "1069",
    name: "Repetitions",
    link: "https://cses.fi/problemset/task/1069",
    acceptedCount: 97004,
    submissionCount: 101235,
    difficulty: 0,
  },
  {
    id: "2079",
    name: "Finding a Centroid",
    link: "https://cses.fi/problemset/task/2079",
    acceptedCount: 5562,
    submissionCount: 5802,
    difficulty: 0,
  },
  {
    id: "2206",
    name: "Pizzeria Queries",
    link: "https://cses.fi/problemset/task/2206",
    acceptedCount: 4947,
    submissionCount: 5157,
    difficulty: 0,
  },
  {
    id: "2165",
    name: "Tower of Hanoi",
    link: "https://cses.fi/problemset/task/2165",
    acceptedCount: 24745,
    submissionCount: 25777,
    difficulty: 0,
  },
  {
    id: "1745",
    name: "Money Sums",
    link: "https://cses.fi/problemset/task/1745",
    acceptedCount: 29157,
    submissionCount: 30369,
    difficulty: 0,
  },
  {
    id: "1730",
    name: "Nim Game I",
    link: "https://cses.fi/problemset/task/1730",
    acceptedCount: 3909,
    submissionCount: 4065,
    difficulty: 0,
  },
  {
    id: "1683",
    name: "Planets and Kingdoms",
    link: "https://cses.fi/problemset/task/1683",
    acceptedCount: 9260,
    submissionCount: 9626,
    difficulty: 0,
  },
  {
    id: "1666",
    name: "Building Roads",
    link: "https://cses.fi/problemset/task/1666",
    acceptedCount: 37988,
    submissionCount: 39486,
    difficulty: 0,
  },
  {
    id: "2183",
    name: "Missing Coin Sum",
    link: "https://cses.fi/problemset/task/2183",
    acceptedCount: 25859,
    submissionCount: 26877,
    difficulty: 0,
  },
  {
    id: "1094",
    name: "Increasing Array",
    link: "https://cses.fi/problemset/task/1094",
    acceptedCount: 90980,
    submissionCount: 94523,
    difficulty: 0,
  },
  {
    id: "1652",
    name: "Forest Queries",
    link: "https://cses.fi/problemset/task/1652",
    acceptedCount: 16604,
    submissionCount: 17250,
    difficulty: 0,
  },
  {
    id: "2193",
    name: "Polygon Lattice Points",
    link: "https://cses.fi/problemset/task/2193",
    acceptedCount: 1944,
    submissionCount: 2019,
    difficulty: 0,
  },
  {
    id: "1676",
    name: "Road Construction",
    link: "https://cses.fi/problemset/task/1676",
    acceptedCount: 14245,
    submissionCount: 14761,
    difficulty: 0,
  },
  {
    id: "1645",
    name: "Nearest Smaller Values",
    link: "https://cses.fi/problemset/task/1645",
    acceptedCount: 17898,
    submissionCount: 18545,
    difficulty: 0,
  },
  {
    id: "1072",
    name: "Two Knights",
    link: "https://cses.fi/problemset/task/1072",
    acceptedCount: 42803,
    submissionCount: 44246,
    difficulty: 0,
  },
  {
    id: "1070",
    name: "Permutations",
    link: "https://cses.fi/problemset/task/1070",
    acceptedCount: 79821,
    submissionCount: 82425,
    difficulty: 0,
  },
  {
    id: "1638",
    name: "Grid Paths",
    link: "https://cses.fi/problemset/task/1638",
    acceptedCount: 44422,
    submissionCount: 45813,
    difficulty: 0,
  },
  {
    id: "1622",
    name: "Creating Strings",
    link: "https://cses.fi/problemset/task/1622",
    acceptedCount: 34903,
    submissionCount: 35886,
    difficulty: 0,
  },
  {
    id: "2076",
    name: "Necessary Roads",
    link: "https://cses.fi/problemset/task/2076",
    acceptedCount: 1637,
    submissionCount: 1679,
    difficulty: 0,
  },
  {
    id: "1649",
    name: "Dynamic Range Minimum Queries",
    link: "https://cses.fi/problemset/task/1649",
    acceptedCount: 20336,
    submissionCount: 20843,
    difficulty: 0,
  },
  {
    id: "1729",
    name: "Stick Game",
    link: "https://cses.fi/problemset/task/1729",
    acceptedCount: 2957,
    submissionCount: 3029,
    difficulty: 0,
  },
  {
    id: "1630",
    name: "Tasks and Deadlines",
    link: "https://cses.fi/problemset/task/1630",
    acceptedCount: 18181,
    submissionCount: 18596,
    difficulty: 0,
  },
  {
    id: "1637",
    name: "Removing Digits",
    link: "https://cses.fi/problemset/task/1637",
    acceptedCount: 46974,
    submissionCount: 48029,
    difficulty: 0,
  },
  {
    id: "1624",
    name: "Chessboard and Queens",
    link: "https://cses.fi/problemset/task/1624",
    acceptedCount: 20648,
    submissionCount: 21059,
    difficulty: 0,
  },
  {
    id: "1650",
    name: "Range Xor Queries",
    link: "https://cses.fi/problemset/task/1650",
    acceptedCount: 21027,
    submissionCount: 21332,
    difficulty: 0,
  },
];
